version: 0.2

phases:

  install: 
    runtime-versions:
      nodejs: latest 
    commands:
      - npm install -g @angular/cli
      - cd app
      - npm install

  
  build:
    commands:
      - ng build --output-hashing none
      - aws s3 cp ./dist/app/ s3://${APPLICATION}-web/ --recursive